.TH SWAPROOTNAME 1 swaprootname\-VERSION
.SH NAME
swaprootname \- root window name swapper
.SH SYNOPSIS
.B swaprootname [
.I new-name
.B ]
.SH DESCRIPTION
.B swaprootname
changes root window name in Unicode-friendly manner. It means that every
application that is capable of displaying UTF-8 strings is also able to
display it properly.
This program is mainly intended for use with
.BR dwm (1)
to change its "status line", permanently or temporarily.
.SH PARAMETERS
.IP new-name
Permanent mode: set root window name to
.i new-name,
permanently.
.IP "empty command line"
Temporary mode:
1. Save away root window name.
2. Wait on
.I stdin
for lines; for every line received, immediately set root window name to that
line. On end-of-file received, revert root window name back to original.
.SH SEE ALSO
.BR dwmstatus (1)
